### ISSUE TITLE
Dragcheck on WordPress Backend

### ISSUE THREAD

**Issue by X-Raym** [arch-stack/dragcheck#3]
Hi !

This is not an issue, just a showcase of what I have done with your script :santa: 

[Dragcheck Admin Rows — My First WordPress Plugin on Official Repository](http://www.extremraym.com/en/wordpress-dragcheck-admin-rows/)

Thanks for sharing your script in the first place ! :+1: 

Cheers !

**Comment by arch-stack** [comment]
Nice, glad to see it being used :smile:
